### ISSUE TITLE
How do you set variables?

### ISSUE THREAD

**Issue by spuder** [echohack/pan#2]
Trying to get a generator created. 

How can I set the variables that are in the erb templates? 

For example, I want to change 'copyright_holder' to my company name.

**Comment by echohack** [comment]
@spuder Sorry for taking so long to answer this!

You should be able to do this through the regular command line arguements. See here: https://docs.chef.io/ctl_chef.html#chef-generate-cookbook

Otherwise, if your company has a single standard that you will always use, you can simply hardcode your own standard and use that instead. (Recommended)
